### ISSUE TITLE
feat: statics and metrics

### ISSUE THREAD

**Issue by MrCroxx** [MrCroxx/foyer#24]
Statics and metrics are needed for better observation.
- [ ] Eviction policy statics 
- [ ] Storage engine statics (for admission policy and reinsertion policy)
- [ ] Storage engine metrics
