### ISSUE TITLE
tracking: make foyer compatible with stable rust

### ISSUE THREAD

**Issue by MrCroxx** [MrCroxx/foyer#310]
- [x] trait_alias
- [x] lint_reasons
- [x] bound_map
- [x] associated_type_defaults
- [x] cfg_match
- [x] let_chains
- [x] offset_of
- [x] associated_type_bounds
- [x] ptr_metadata
- [x] allocator_api
- [x] strict_provenance
- [x] get_mut_unchecked
- [x] error_generic_member_access
- [x] lazy_cell
- [x] box_into_inner
- [x] try_trait_v2
- [x] pattern

**Comment by xiaguan** [comment]
for offset_of , it seems already stable ?
https://github.com/rust-lang/rust/issues/106655

**Comment by MrCroxx** [comment]
> for offset_of , it seems already stable ? [rust-lang/rust#106655](https://github.com/rust-lang/rust/issues/106655)

Yep. But currently foyer is using the same rust-chain with RisingWave. I'm working on decoupling.

**Comment by MrCroxx** [comment]
Done via #317
