### ISSUE TITLE
tracking: improve the API to make foyer more user-friendly

### ISSUE THREAD

**Issue by MrCroxx** [MrCroxx/foyer#327]
- [x] Remove unnecessary generic type.
- [x] Better cache builder for in-memory cache. #350 
- [x] Better cache builder for disk cache. #369 
- [x] Refine and unify the `Key` `Value` abstraction of im-memory cache and disk cache. #366 
- [x] Unify in-memory cache and disk cache build. #391
