### ISSUE TITLE
tracking: compression

### ISSUE THREAD

**Issue by MrCroxx** [MrCroxx/foyer#49]
Roadmap:
- ~Alter `apply` writer allocation size according to compressed size.~ (write model modified with ring buffer, not planed)
- [x] Alter rate limit algorithm to handle actual rate != expected rate.
- [x] Add compression support. #198 
- [x] Refine bench tool data generator to adapt to compression. #204

**Comment by MrCroxx** [comment]
Completed.
